sudo: true

addons:
  sonarqube: true

cache:
  directories:
    - modules/client/node_modules
    - .autoconf
    - $HOME/.m2

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

install:
  - nvm install 6
  - nvm use 6
  - cd ./modules/client
  - npm install
  - npm run start
  - npm run test
  - npm run e2e
  - cd ./../..

notifications:
  email:
    recipients:
      - info@smsc.io
      - dimakuba124@gmail.com
    on_success: always
    on_failure: always

addons:
  sonarqube: true
  sauce_connect: true