sudo: required

addons:
  sonarqube: true

cache:
  directories:
    - modules/client/node_modules
    - .autoconf
    - $HOME/.m2

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb

install:
  - nvm install 6
  - nvm use 6
  - cd modules/client && npm install

before_script:
  - npm start&
  - sleep 25

script:
  - npm run test
  - npm run e2e

notifications:
  email:
    recipients:
      - info@smsc.io
      - dimakuba124@gmail.com
    on_success: always
    on_failure: always

addons:
  sonarqube: true
  sauce_connect: true