sudo: true
dist: trusty

addons:
  sonarqube: true

services:
  - mysql
  - docker

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS smsbox;'

cache:
  docker: true
  directories:
    - modules/client/node_modules
    - .autoconf
    - $HOME/.m2

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

install:
  - nvm install 6
  - nvm use 6
  - cd modules/client && npm install
  - cd ../backend && npm install && cd ../client

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    fi
  - mvn clean -DrepoToken=$COVERALLS_REPO_TOKEN cobertura:cobertura coveralls:report

script:
  - npm test
  - npm run start &
  - sleep 50
  - cd ../backend && npm run start &
  - sleep 5
  - cd ../client && npm run e2e
  - cd ../backend && npm run test && cd ..
  - npm run build:docker

notifications:
  email:
    recipients:
      - info@smsc.io
      - dimakuba124@gmail.com
    on_success: always
    on_failure: always

addons:
  sonarqube: true
  sauce_connect: true
