sudo: true
dist: trusty

addons:
  sonarqube: true

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS smsbox;'

cache:
  directories:
    - modules/client/node_modules
    - .autoconf
    - $HOME/.m2

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

install:
  - nvm install 6
  - nvm use 6
  - cd modules/client && npm install
  - cd ../backend && npm install && cd ../client

script:
  - npm test
  - npm run start &
  - sleep 50
  - cd ../backend && npm run start &
  - sleep 5
  - cd ../client && npm run e2e

notifications:
  email:
    recipients:
      - info@smsc.io
      - dimakuba124@gmail.com
    on_success: always
    on_failure: always

addons:
  sonarqube: true
  sauce_connect: true
